// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA69HLh0oiKSQluCQ2ZlPYEO3Y-lzUDwOQ',
    appId: '1:432912095518:web:aaf83314599b35bf7d510f',
    messagingSenderId: '432912095518',
    projectId: 'flutter-test-one-14ced',
    authDomain: 'flutter-test-one-14ced.firebaseapp.com',
    storageBucket: 'flutter-test-one-14ced.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_7DK9N-JJb5pAyY2oDpPJx9CG9jigj6s',
    appId: '1:432912095518:android:70f5932afec80f747d510f',
    messagingSenderId: '432912095518',
    projectId: 'flutter-test-one-14ced',
    storageBucket: 'flutter-test-one-14ced.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3L0q9IB0k9YjTQtzTpae4Q3Yhz5HIcfo',
    appId: '1:432912095518:ios:51f195441e01f57a7d510f',
    messagingSenderId: '432912095518',
    projectId: 'flutter-test-one-14ced',
    storageBucket: 'flutter-test-one-14ced.appspot.com',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3L0q9IB0k9YjTQtzTpae4Q3Yhz5HIcfo',
    appId: '1:432912095518:ios:838e491f219c2a697d510f',
    messagingSenderId: '432912095518',
    projectId: 'flutter-test-one-14ced',
    storageBucket: 'flutter-test-one-14ced.appspot.com',
    iosBundleId: 'com.example.myFlutterApp.RunnerTests',
  );
}
